# Generated by Django 4.2.4 on 2023-09-25 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='fee',
        ),
        migrations.AddField(
            model_name='course',
            name='first_roll',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('finished', 'Finished')], default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_photo',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_photos'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='fee_type',
            field=models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('custom', 'Custom')], default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.AddField(
            model_name='onetimefee',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AddField(
            model_name='onetimefee',
            name='students',
            field=models.ManyToManyField(blank=True, to='main.student'),
        ),
    ]
