# Generated by Django 4.2.4 on 2023-09-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_onetimefee_remove_course_fee_course_first_roll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimefee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='onetimefee',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='onetimefee',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onetimefee',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onetimefee',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
