# Generated by Django 4.2.4 on 2023-08-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_course_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee_type',
            field=models.CharField(choices=[('one-time', 'One-time'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
